version: '3'
services:
  server:
    image: stefanchurch/ferry-services-server:latest
    ports:
      - "3000:3000"
    depends_on:
      - "db"
    restart: always
    env_file:
      - envfile.docker
    command: /opt/ferry-services/ferry-services-server-exe
  event-processor:
    image: stefanchurch/ferry-services-scraper:latest
    depends_on:
      - "db"
    restart: always
    env_file:
      - envfile.docker
    command: /opt/ferry-services/ferry-services-scraper-exe
  db:
    image: "mdillon/postgis"
    environment:
      POSTGRES_DB: ferry-services
    restart: always
    volumes:
      - datavolume:/var/lib/postgresql/data
    env_file:
      - envfile.docker

volumes:
  datavolume:
