version: '3'
services:
  server-test:
    image: stefanchurch/ferry-services-server:latest
    container_name: ferry-services-server-test
    ports:
      - "3008:3008"
    depends_on:
      - "db-test"
    restart: always
    env_file:
      - envfile.docker-test
    tty: true
    command: /opt/ferry-services/ferry-services-server-exe
  scraper-test:
    image: stefanchurch/ferry-services-scraper:latest
    container_name: ferry-services-scraper-test
    depends_on:
      - "db-test"
    restart: always
    env_file:
      - envfile.docker-test
    tty: true
    command: /opt/ferry-services/ferry-services-scraper-exe
  transxchange-fetcher-test:
    image: stefanchurch/transxchange-fetcher:latest
    container_name: transxchange-fetcher-test
    depends_on:
      - "db-test"
    restart: always
    env_file:
      - envfile.docker-test
    tty: true
    command: /opt/ferry-services/transxchange-fetcher-exe
  db-test:
    image: "mdillon/postgis"
    container_name: ferry-services-db-test
    environment:
      POSTGRES_DB: ferry-services-test
    restart: always
    volumes:
      - datavolumetest:/var/lib/postgresql/data
    env_file:
      - envfile.docker-test

volumes:
  datavolumetest:
