name:                ferry-services-server
version:             0.1.0.0
github:              "schurch/ferry-services-server-v2"
license:             BSD3
author:              "Stefan Church"
maintainer:          "stefan.church@gmail.com"
copyright:           "2020 Stefan Church"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ferry-services-server#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson
    - amazonka
    - amazonka-core
    - amazonka-sns
    - binary
    - bytestring
    - containers
    - HTTP
    - lens
    - mtl
    - network-uri
    - postgresql-simple
    - scientific
    - scotty
    - split
    - time
    - tinylog
    - text
    - unordered-containers
    - uuid
    - zlib

executables:
  ferry-services-server-exe:
    main:                Main.hs
    source-dirs:         web-server
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - bytestring
    - data-default
    - fast-logger
    - ferry-services-server
    - mtl
    - raven-haskell
    - scotty
    - time
    - tinylog
    - text
    - unordered-containers
    - wai
    - wai-extra
    - wai-middleware-static
    - warp
    - uuid

  ferry-services-scraper-exe:
    main:                Main.hs
    source-dirs:         scraper
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ferry-services-server
    - raven-haskell
    - tinylog

tests:
  ferry-services-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ferry-services-server
