name:                ferry-services-server
version:             0.1.0.0
github:              "schurch/ferry-services-server-v2"
license:             BSD3
author:              "Stefan Church"
maintainer:          "stefan.church@gmail.com"
copyright:           "2020 Stefan Church"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ferry-services-server#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson
    - amazonka
    - amazonka-core
    - amazonka-sns
    - binary
    - bytestring
    - cassava
    - containers
    - data-default
    - directory
    - fast-logger
    - haskell-postgis
    - http-types
    - http-conduit
    - lens
    - MissingH
    - network
    - mtl
    - postgresql-simple
    - regex-compat
    - resource-pool
    - scientific
    - scotty
    - tagsoup
    - time
    - tinylog
    - text
    - unordered-containers
    - uuid
    - vector
    - wai
    - wai-cors
    - wai-extra
    - wai-middleware-static
    - warp
    - xml
    - zip

executables:
  ferry-services-server-exe:
    main:                Main.hs
    source-dirs:         web-server
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - bytestring
    - ferry-services-server
    - mtl
    - postgresql-simple
    - raven-haskell
    - resource-pool
    - scotty
    - tinylog
    - text
    - unordered-containers
    - wai
    - wai-extra
    - warp

  ferry-services-scraper-exe:
    main:                Main.hs
    source-dirs:         scraper
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ferry-services-server
    - postgresql-simple
    - raven-haskell
    - resource-pool
    - tinylog
    - transformers

  ferry-services-weather-fetcher-exe:
    main:                Main.hs
    source-dirs:         weather-fetcher
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ferry-services-server
    - postgresql-simple
    - raven-haskell
    - resource-pool
    - tinylog
    - transformers

  ferry-services-vessel-fetcher-exe:
    main:                Main.hs
    source-dirs:         vessel-fetcher
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ferry-services-server
    - postgresql-simple
    - raven-haskell
    - resource-pool
    - tinylog
    - transformers

  ferry-services-transxchange-ingester-exe:
    main:                Main.hs
    source-dirs:         transxchange-ingester
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ferry-services-server
    - postgresql-simple
    - raven-haskell
    - resource-pool
    - tinylog
    - transformers

tests:
  ferry-services-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - aeson-qq
    - ferry-services-server
    - hspec
    - hspec-wai
    - hspec-wai-json
    - http-types
    - mtl
    - postgresql-simple
    - resource-pool
    - scotty
    - time
    - tinylog
    - wai
    - wai-extra
