BEGIN;

UPDATE transxchange_services SET service_id = NULL WHERE service_code = 'FSBCM04';
UPDATE transxchange_services SET service_id = NULL WHERE service_code = 'FSAO020A';
UPDATE transxchange_services SET service_id = NULL WHERE service_code = 'FSACM15';
UPDATE transxchange_services SET service_id = NULL WHERE service_code = 'FSACM16';
UPDATE transxchange_services SET service_id = NULL WHERE service_code = 'FSACM05A';
UPDATE transxchange_services SET service_id = NULL WHERE service_code = 'FSACM02';
UPDATE transxchange_services SET service_id = NULL WHERE service_code = 'FSACM01';
UPDATE transxchange_services SET service_id = NULL WHERE service_code = 'FSACM21';
UPDATE transxchange_services SET service_id = NULL WHERE service_code = 'FSAO015A';
UPDATE transxchange_services SET service_id = NULL WHERE service_code = 'FSACM19';
UPDATE transxchange_services SET service_id = NULL WHERE service_code = 'FSACM17';
UPDATE transxchange_services SET service_id = NULL WHERE service_code = 'FSACM22';
UPDATE transxchange_services SET service_id = NULL WHERE service_code = 'FSACM14';
UPDATE transxchange_services SET service_id = NULL WHERE service_code = 'FSACM13';
UPDATE transxchange_services SET service_id = NULL WHERE service_code = 'FSACM12';
UPDATE transxchange_services SET service_id = NULL WHERE service_code = 'FSACM23';
UPDATE transxchange_services SET service_id = NULL WHERE service_code = 'FSACM10';
UPDATE transxchange_services SET service_id = NULL WHERE service_code = 'FSACM08';
UPDATE transxchange_services SET service_id = NULL WHERE service_code = 'FSACM06';
UPDATE transxchange_services SET service_id = NULL WHERE service_code = 'FSACM01A';
UPDATE transxchange_services SET service_id = NULL WHERE service_code = 'FSACM20';
UPDATE transxchange_services SET service_id = NULL WHERE service_code = 'FSACM18';

UPDATE locations SET stop_point_id = NULL WHERE location_id = 45;
UPDATE locations SET stop_point_id = NULL WHERE location_id = 17;
UPDATE locations SET stop_point_id = NULL WHERE location_id = 40;
UPDATE locations SET stop_point_id = NULL WHERE location_id = 53;
UPDATE locations SET stop_point_id = NULL WHERE location_id = 49;
UPDATE locations SET stop_point_id = NULL WHERE location_id = 20;
UPDATE locations SET stop_point_id = NULL WHERE location_id = 52;
UPDATE locations SET stop_point_id = NULL WHERE location_id = 22;
UPDATE locations SET stop_point_id = NULL WHERE location_id = 24;
UPDATE locations SET stop_point_id = NULL WHERE location_id = 57;
UPDATE locations SET stop_point_id = NULL WHERE location_id = 46;
UPDATE locations SET stop_point_id = NULL WHERE location_id = 18;
UPDATE locations SET stop_point_id = NULL WHERE location_id = 34;
UPDATE locations SET stop_point_id = NULL WHERE location_id = 51;
UPDATE locations SET stop_point_id = NULL WHERE location_id = 54;
UPDATE locations SET stop_point_id = NULL WHERE location_id = 31;
UPDATE locations SET stop_point_id = NULL WHERE location_id = 56;
UPDATE locations SET stop_point_id = NULL WHERE location_id = 35;
UPDATE locations SET stop_point_id = NULL WHERE location_id = 55;
UPDATE locations SET stop_point_id = NULL WHERE location_id = 14;
UPDATE locations SET stop_point_id = NULL WHERE location_id = 58;
UPDATE locations SET stop_point_id = NULL WHERE location_id = 41;
UPDATE locations SET stop_point_id = NULL WHERE location_id = 37;
UPDATE locations SET stop_point_id = NULL WHERE location_id = 50;
UPDATE locations SET stop_point_id = NULL WHERE location_id = 21;
UPDATE locations SET stop_point_id = NULL WHERE location_id = 39;
UPDATE locations SET stop_point_id = NULL WHERE location_id = 16;
UPDATE locations SET stop_point_id = NULL WHERE location_id = 44;
UPDATE locations SET stop_point_id = NULL WHERE location_id = 47;
UPDATE locations SET stop_point_id = NULL WHERE location_id = 29;
UPDATE locations SET stop_point_id = NULL WHERE location_id = 43;
UPDATE locations SET stop_point_id = NULL WHERE location_id = 23;
UPDATE locations SET stop_point_id = NULL WHERE location_id = 48;
UPDATE locations SET stop_point_id = NULL WHERE location_id = 42;
UPDATE locations SET stop_point_id = NULL WHERE location_id = 33;
UPDATE locations SET stop_point_id = NULL WHERE location_id = 15;
UPDATE locations SET stop_point_id = NULL WHERE location_id = 30;
UPDATE locations SET stop_point_id = NULL WHERE location_id = 25;
UPDATE locations SET stop_point_id = NULL WHERE location_id = 13;
UPDATE locations SET stop_point_id = NULL WHERE location_id = 32;

DELETE FROM service_locations WHERE service_id = 22 AND location_id = 33;

COMMIT;
