BEGIN;

UPDATE transxchange_services SET service_id = 4 WHERE service_code = 'FSBCM04';
UPDATE transxchange_services SET service_id = 37 WHERE service_code = 'FSAO020A';
UPDATE transxchange_services SET service_id = 15 WHERE service_code = 'FSACM15';
UPDATE transxchange_services SET service_id = 16  WHERE service_code = 'FSACM16';
UPDATE transxchange_services SET service_id = 36 WHERE service_code = 'FSACM05A';
UPDATE transxchange_services SET service_id = 2 WHERE service_code = 'FSACM02';
UPDATE transxchange_services SET service_id = 1 WHERE service_code = 'FSACM01';
UPDATE transxchange_services SET service_id = 21 WHERE service_code = 'FSACM21';
UPDATE transxchange_services SET service_id = 38 WHERE service_code = 'FSAO015A';
UPDATE transxchange_services SET service_id = 19  WHERE service_code = 'FSACM19';
UPDATE transxchange_services SET service_id = 17 WHERE service_code = 'FSACM17';
UPDATE transxchange_services SET service_id = 22 WHERE service_code = 'FSACM22';
UPDATE transxchange_services SET service_id = 14 WHERE service_code = 'FSACM14';
UPDATE transxchange_services SET service_id = 13 WHERE service_code = 'FSACM13';
UPDATE transxchange_services SET service_id = 12 WHERE service_code = 'FSACM12';
UPDATE transxchange_services SET service_id = 23 WHERE service_code = 'FSACM23';
UPDATE transxchange_services SET service_id = 10 WHERE service_code = 'FSACM10';
UPDATE transxchange_services SET service_id = 8 WHERE service_code = 'FSACM08';
UPDATE transxchange_services SET service_id = 6 WHERE service_code = 'FSACM06';
UPDATE transxchange_services SET service_id = 39 WHERE service_code = 'FSACM01A';
UPDATE transxchange_services SET service_id = 20 WHERE service_code = 'FSACM20';
UPDATE transxchange_services SET service_id = 18 WHERE service_code = 'FSACM18';

UPDATE locations SET stop_point_id = '9300ARM' WHERE location_id = 45;
UPDATE locations SET stop_point_id = '9300AHB' WHERE location_id = 17;
UPDATE locations SET stop_point_id = '9300BNY' WHERE location_id = 40;
UPDATE locations SET stop_point_id = '9300CPB' WHERE location_id = 53;
UPDATE locations SET stop_point_id = '9300CAN' WHERE location_id = 49;
UPDATE locations SET stop_point_id = '9300CBA' WHERE location_id = 20;
UPDATE locations SET stop_point_id = '9300CLB' WHERE location_id = 52;
UPDATE locations SET stop_point_id = '9300COT' WHERE location_id = 22;
UPDATE locations SET stop_point_id = '9300COL' WHERE location_id = 24;
UPDATE locations SET stop_point_id = '9300DNU' WHERE location_id = 57;
UPDATE locations SET stop_point_id = '9300GAL' WHERE location_id = 46;
UPDATE locations SET stop_point_id = '9300ERI' WHERE location_id = 18;
UPDATE locations SET stop_point_id = '9300FIO' WHERE location_id = 34;
UPDATE locations SET stop_point_id = '9300FIB' WHERE location_id = 51;
UPDATE locations SET stop_point_id = '9300OKF' WHERE location_id = 54;
UPDATE locations SET stop_point_id = '9300AMH' WHERE location_id = 31;
UPDATE locations SET stop_point_id = '9300GUR' WHERE location_id = 56;
UPDATE locations SET stop_point_id = '9300IOA' WHERE location_id = 35;
UPDATE locations SET stop_point_id = '9300KER' WHERE location_id = 55;
UPDATE locations SET stop_point_id = '9300KLB' WHERE location_id = 14;
UPDATE locations SET stop_point_id = '9300KGN' WHERE location_id = 58;
UPDATE locations SET stop_point_id = '9300LEV' WHERE location_id = 41;
UPDATE locations SET stop_point_id = '9300LMR' WHERE location_id = 37;
UPDATE locations SET stop_point_id = '9300LHL' WHERE location_id = 50;
UPDATE locations SET stop_point_id = '9300LBS' WHERE location_id = 21;
UPDATE locations SET stop_point_id = '9300LMA' WHERE location_id = 39;
UPDATE locations SET stop_point_id = '9300LCR' WHERE location_id = 16;
UPDATE locations SET stop_point_id = '9300MLG' WHERE location_id = 44;
UPDATE locations SET stop_point_id = '9300PTM' WHERE location_id = 47;
UPDATE locations SET stop_point_id = '9300PAV' WHERE location_id = 29;
UPDATE locations SET stop_point_id = '9300RAA' WHERE location_id = 43;
UPDATE locations SET stop_point_id = '9300RHU' WHERE location_id = 23;
UPDATE locations SET stop_point_id = '9300KLH' WHERE location_id = 48;
UPDATE locations SET stop_point_id = '9300SCO' WHERE location_id = 42;
UPDATE locations SET stop_point_id = '9300TAB' WHERE location_id = 33;
UPDATE locations SET stop_point_id = '9300LCT' WHERE location_id = 15;
UPDATE locations SET stop_point_id = '9300TYL' WHERE location_id = 30;
UPDATE locations SET stop_point_id = '9300TRE' WHERE location_id = 25;
UPDATE locations SET stop_point_id = '9300TOB' WHERE location_id = 13;
UPDATE locations SET stop_point_id = '9300UIG' WHERE location_id = 32;

INSERT INTO service_locations (service_id, location_id) VALUES (22, 33);

COMMIT;
