version: '3'
services:
  server-test:
    image: stefanchurch/ferry-services-server:latest
    container_name: ferry-services-server-test
    ports:
      - "127.0.0.1:3008:3008"
    depends_on:
      - "db-test"
    restart: always
    env_file:
      - envfile.docker-test
    tty: true
    command: /opt/ferry-services/ferry-services-server-exe
  scraper-test:
    image: stefanchurch/ferry-services-scraper:latest
    container_name: ferry-services-scraper-test
    depends_on:
      - "db-test"
    restart: always
    env_file:
      - envfile.docker-test
    tty: true
    command: /opt/ferry-services/ferry-services-scraper-exe
  weather-fetcher-test:
    image: stefanchurch/ferry-services-weather-fetcher:latest
    container_name: ferry-services-weather-fetcher-test
    depends_on:
      - "db-test"
    restart: always
    env_file:
      - envfile.docker-test
    tty: true
    command: /opt/ferry-services/ferry-services-weather-fetcher-exe
  vessel-fetcher-test:
    image: stefanchurch/ferry-services-vessel-fetcher:latest
    container_name: ferry-services-vessel-fetcher-test
    depends_on:
      - "db-test"
    restart: always
    env_file:
      - envfile.docker-test
    tty: true
    command: /opt/ferry-services/ferry-services-vessel-fetcher-exe
  rail-departure-fetcher-test:
    image: stefanchurch/ferry-services-rail-departure-fetcher:latest
    container_name: ferry-services-rail-departure-fetcher-test
    depends_on:
      - "db-test"
    restart: always
    env_file:
      - envfile.docker-test
    tty: true
    command: /opt/ferry-services/ferry-services-rail-departure-fetcher-exe
  transxchange-ingester-test:
    image: stefanchurch/ferry-services-transxchange-ingester:latest
    container_name: ferry-services-transxchange-ingester-test
    depends_on:
      - "db-test"
    restart: always
    env_file:
      - envfile.docker-test
    tty: true
    command: /opt/ferry-services/ferry-services-transxchange-ingester-exe
  db-test:
    image: "mdillon/postgis"
    container_name: ferry-services-db-test
    environment:
      POSTGRES_DB: ferry-services-test
    restart: always
    volumes:
      - datavolumetest:/var/lib/postgresql/data
    env_file:
      - envfile.docker-test

volumes:
  datavolumetest:
