version: '3'

x-ferry-common: &ferry-common
  env_file:
    - envfile.docker-prod
  environment:
    DB_CONNECTION: /opt/ferry-services/data/ferry-services.sqlite3
  image: stefanchurch/ferry-services:latest
  volumes:
    - ./data:/opt/ferry-services/data
  restart: always
  tty: true

services:
  server-prod:
    <<: *ferry-common
    container_name: ferry-services-server-prod
    ports:
      - "127.0.0.1:3009:3009"
    volumes:
      - ./data:/opt/ferry-services/data
      - ./offline:/opt/ferry-services/offline
    command: /opt/ferry-services/ferry-services-server-exe

  scraper-prod:
    <<: *ferry-common
    container_name: ferry-services-scraper-prod
    command: /opt/ferry-services/ferry-services-scraper-exe

  timetable-document-scraper-prod:
    <<: *ferry-common
    container_name: ferry-services-timetable-document-scraper-prod
    command: /opt/ferry-services/ferry-services-timetable-document-scraper-exe

  weather-fetcher-prod:
    <<: *ferry-common
    container_name: ferry-services-weather-fetcher-prod
    command: /opt/ferry-services/ferry-services-weather-fetcher-exe

  vessel-fetcher-prod:
    <<: *ferry-common
    container_name: ferry-services-vessel-fetcher-prod
    command: /opt/ferry-services/ferry-services-vessel-fetcher-exe

  rail-departure-fetcher-prod:
    <<: *ferry-common
    container_name: ferry-services-rail-departure-fetcher-prod
    command: /opt/ferry-services/ferry-services-rail-departure-fetcher-exe

  transxchange-ingester-prod:
    <<: *ferry-common
    container_name: ferry-services-transxchange-ingester-prod
    volumes:
      - ./data:/opt/ferry-services/data
      - ./offline:/opt/ferry-services/offline
    command: /opt/ferry-services/ferry-services-transxchange-ingester-v2-exe
