scrape_configs:
- job_name: cadvisor
  scrape_interval: 30s
  static_configs:
    - targets:
      - localhost:8080

- job_name: node-exporter
  scrape_interval: 30s
  static_configs:
    - targets:
      - localhost:9100

- job_name: grok-exporter
  scrape_interval: 30s
  static_configs:
    - targets:
      - localhost:9144

- job_name: "prometheus"
  scrape_interval: 1m
  static_configs:
    - targets: 
      - localhost:9090
  basic_auth:
      username: 
      password:
